### ISSUE TITLE
Windows 10 Server

### ISSUE THREAD

**Issue by wiksito** [koreader/koreader-sync-server#12]
Hi, is there instructions to run this on Windows 10? I tried the the instructions with Docker for Windows but could not get to the second step.

# for production, we mount redis data volume to persist state
mkdir -p ./logs/{redis,app} ./data/redis
docker run -d -p 7200:7200 \
    -v `pwd`/logs/app:/app/koreader-sync-server/logs \
    -v `pwd`/logs/redis:/var/log/redis \
    -v `pwd`/data/redis:/var/lib/redis \
    --name=kosync koreader/kosync:latest

I could run the check though:
curl -k -v -H "Accept: application/vnd.koreader.v1+json" https://localhost:7200/healthcheck
# should return {"state":"OK"}

Thanks for your help and sorry I have no idea what I'm doing but would like to host my own server.

**Comment by MelleKoning** [comment]
in powershell you have to replace the `pwd` with a simple `.` (dot) to refer to the local folder, and for windows we need to swap the slash for paths to a backslash 

# startup koreader sync in powershell
 docker run -d -p 7200:7200 -v .\logs\app:/app/koreader-sync-server/logs -v .\logs\redis:/var/log/redis -v .\data\redis:/var/lib/redis --name=kosync koreader/kosync:latest

This worked in windows 10 powershell with docker desktop
