### ISSUE TITLE
Server not starting at boot

### ISSUE THREAD

**Issue by Jbbrack03** [koreader/koreader-sync-server#13]
I'm not completely sure if this is intended, but the server is not starting when I reboot the system. I have to manually remove the existing container and install everything again with each boot. Is this expected?

**Comment by Frenzie** [comment]
If you add `--restart=always` Docker will automatically do so. Alternatively you can manually make a systemd service out of it, see for example https://github.com/koreader/koreader-misc/blob/e555d777705465afaa1489e179ba7e742bed6dac/services/kosync.service and https://github.com/koreader/koreader-misc/blob/e555d777705465afaa1489e179ba7e742bed6dac/services/enable-ko-services.sh#L3
