### ISSUE TITLE
armv7 compatibility

### ISSUE THREAD

**Issue by Edo78** [koreader/koreader-sync-server#16]
Hi,

trying to install the sync server on my Raspberry Pi 4 I noticed that it's not compatible.

Should be possible to have a docker image that support arm processors?

**Comment by Edo78** [comment]
I usually prefer to use docker images for my self hosted services but thank you for your suggestion :+1:

**Comment by Frenzie** [comment]
Compatibility fixed in https://github.com/koreader/koreader-sync-server/commit/5b578fb513c2ad771efdfececc9ecb3ac605de7f
