### ISSUE TITLE
Where to put the Custom Sync Server?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader-sync-server#3]
Hi

I installed the custom sync server but I am unable to locate the place where I need to put the url of my custom server. I look into the advanced settings without any luck

**Comment by chrox** [comment]
It's the "Custom sync server" menu entry.

![screenshot from 2015-10-06 00 28 55](https://cloud.githubusercontent.com/assets/751535/10286674/7c053bfc-6bc1-11e5-96d2-71e80c637b11.png)

**Comment by gerroon** [comment]
It is not listed on Kobo Glo.

I only have Register/Autosync/Sync Now

**Comment by chrox** [comment]
I just published a new nightly build release this feature should be there.

**Comment by gerroon** [comment]
@chrox 

Thanks for ther update.
